/**
 * Auto-generated version file
 * Generated at: 2026-01-26T10:11:27.256Z
 * DO NOT EDIT - This file is automatically generated by rls.js
 */

export const VERSION = '4.1.0.260126.9266cc8';
export const PACKAGE_VERSION = '4.1.0';
export const BUILD_TIMESTAMP = '260126';
export const GIT_SHA = '9266cc8';
export const BUILD_DATE = '2026-01-26T10:11:27.256Z';
