/**
 * Auto-generated version file
 * Generated at: 2026-02-02T11:37:08.679Z
 * DO NOT EDIT - This file is automatically generated by rls.js
 */

export const VERSION = '4.1.3.260202.23e4c59';
export const PACKAGE_VERSION = '4.1.3';
export const BUILD_TIMESTAMP = '260202';
export const GIT_SHA = '23e4c59';
export const BUILD_DATE = '2026-02-02T11:37:08.679Z';
