/**
 * Auto-generated version file
 * Generated at: 2026-01-30T06:41:09.507Z
 * DO NOT EDIT - This file is automatically generated by rls.js
 */

export const VERSION = '4.1.2.260130.77d6a20';
export const PACKAGE_VERSION = '4.1.2';
export const BUILD_TIMESTAMP = '260130';
export const GIT_SHA = '77d6a20';
export const BUILD_DATE = '2026-01-30T06:41:09.507Z';
